#Splash screen properties
#Wed Aug 12 10:20:41 ICT 2026
logoTexture=textures/gui/title/mojang.png
background=0x0964DB
font=0x0
barBackground=0xE00000
barBorder=0x000000
rotate=true
bar=0xEDE909
enabled=true
resourcePackPath=resources
logoOffset=0
forgeTexture=fml\:textures/gui/forge.gif
fontTexture=textures/font/ascii.png
